[build]
builder = "nixpacks"

[build.nixpacks]
aptPkgs = ["chromium", "fonts-noto-cjk"]

[deploy]
startCommand = "export CHROMIUM_PATH=$(which chromium-browser || which chromium) && npx prisma db push && npm start"
